"""Service modules for AI Sprint."""

from ai_sprint.services.convoy_allocator import (
    allocate_next_convoy,
    check_convoy_dependencies_met,
    get_blocked_convoys,
    unblock_dependent_convoys,
    update_blocked_convoys_status,
)
from ai_sprint.services.worktree_manager import WorktreeManager
from ai_sprint.services.session_manager import (
    SessionManager,
    capture_session_logs,
    disable_pane_logging,
    enable_pane_logging,
    get_pane_content,
    get_pane_log_path,
    send_command_to_pane,
    spawn_agent,
)
from ai_sprint.services.state_manager import (
    VALID_TASK_TRANSITIONS,
    acknowledge_event,
    add_file_to_convoy,
    check_convoy_completion,
    check_feature_completion,
    check_file_overlap,
    claim_task_atomic,
    cleanup_feature,
    consume_events,
    create_convoy,
    create_feature,
    create_schema,
    create_task,
    get_convoy,
    get_convoy_files,
    get_current_version,
    get_db,
    get_feature,
    get_pending_event_count,
    get_task,
    increment_task_failure_count,
    initialize_database,
    list_convoys_by_feature,
    list_features_by_status,
    list_tasks_by_convoy,
    migrate,
    publish_event,
    reject_task,
    remove_file_from_convoy,
    transition_task_status,
    update_convoy_files,
    update_convoy_status,
    update_feature_status,
    update_task_status,
    update_task_validation_results,
    validate_convoy_files_no_overlap,
    validate_no_file_conflicts,
    validate_task_transition,
)

__all__ = [
    # Convoy allocation
    "allocate_next_convoy",
    "check_convoy_dependencies_met",
    "get_blocked_convoys",
    "unblock_dependent_convoys",
    "update_blocked_convoys_status",
    # Worktree management
    "WorktreeManager",
    # Session management
    "SessionManager",
    "capture_session_logs",
    "disable_pane_logging",
    "enable_pane_logging",
    "get_pane_content",
    "get_pane_log_path",
    "send_command_to_pane",
    "spawn_agent",
    # State management - CRUD
    "acknowledge_event",
    "add_file_to_convoy",
    "claim_task_atomic",
    "consume_events",
    "create_convoy",
    "create_feature",
    "create_schema",
    "create_task",
    "get_convoy",
    "get_convoy_files",
    "get_current_version",
    "get_db",
    "get_feature",
    "get_pending_event_count",
    "get_task",
    "increment_task_failure_count",
    "initialize_database",
    "list_convoys_by_feature",
    "list_features_by_status",
    "list_tasks_by_convoy",
    "migrate",
    "publish_event",
    "remove_file_from_convoy",
    "update_convoy_files",
    "update_convoy_status",
    "update_feature_status",
    "update_task_status",
    "update_task_validation_results",
    # State management - State machine
    "VALID_TASK_TRANSITIONS",
    "check_convoy_completion",
    "check_feature_completion",
    "check_file_overlap",
    "cleanup_feature",
    "reject_task",
    "transition_task_status",
    "validate_convoy_files_no_overlap",
    "validate_no_file_conflicts",
    "validate_task_transition",
]
